const state = {
  isSpinnerLoading: false,
  photo1: '',
  photo2: '',
  photo3: '',
  isPhotoOneUploaded: false,
  isPhotoTwoUploaded: false,
  isPhotoThreeUploaded: false,
  name: '',
  category: '',
  price: '',
  unit: '',
  stock: '',
  description: '',
  specs: '',
  isNameValid: false,
  isCategoryValid: false,
  isPriceValid: false,
  isUnitValid: false,
  isStockValid: false,
  isDescriptionValid: false,
  isSpecsValid: false,
  isNameChanged: false,
  isCategoryChanged: false,
  isPriceChanged: false,
  isUnitChanged: false,
  isStockChanged: false,
  isDescriptionChanged: false,
  isSpecsChanged: false,
};

export default state;
